### PR TITLE
Remove PII from device user agent string

### PR DESCRIPTION
**Pull request by luckyrat**
See #39

### CODE REVIEW

**Comment by TesteurManiak** [comment]
As this solve the same issue as #41 all changes should be in the same PR.

**Comment by luckyrat** [comment]
I figured that the two components of the fix for that issue might take a different amount of time to discuss, refine and test so created separate PRs for each commit but I'm happy to combine them into one PR if you prefer, once you're satisfied that they will both be accepted at the same time.

**Comment by TesteurManiak** [comment]
Yeah, I prefer having only on PR per issue to be able to check all code changes at one place. Thanks!

**Comment by luckyrat** [comment]
I've rebased to the latest main and included the commit from #41 as requested.

**Review by TesteurManiak — APPROVED** [review]

**Pull request merged**
