### PR TITLE
Implemented campaigns and tests in style of EventInfo tests

### PR DESCRIPTION
**Pull request by EPNW-Eric**
We want to distinguish between app entries by clicking on a notification and normal launches. After reading a bit more about the different tracking techniques we figured that we should model these entires using acquisition channels. Therefor, we need campaigns.

The idea was now to add an optional campaign parameter to `trackScreenWithName` calls and the `TraceableClientMixin`.

This time, I tried to provide some tests and took the tests for `EventInfo` as orientation, since the new `Campaign` class is also just a data object for most parts.

### CODE REVIEW

**Comment by TesteurManiak** [comment]
I've added an utility method which simplifies a bit error checking this might help reduce the boilerplate in `Campaign`: https://github.com/Floating-Dartists/matomo-tracker/pull/68/commits/1d83becd4b906515506854f82356f3d015c7da0f

**Comment by EPNW-Eric** [comment]
I will incorporate that 👍

**Review by TesteurManiak — APPROVED** [review]
LGTM! But we should wait for #68 to be merged first

**Comment by TesteurManiak** [comment]
Oops sorry @EPNW-Eric, seems like your PRs targeting `#65_update-parameters` have been closed with its merge in dev (you might be able to re-open it by targeting `dev`)

**Pull request closed without merging**
