### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by lsaudon**
Update dependencies to be able to update `device_info_plus` in my project.

### CODE REVIEW

**Comment by M123-dev** [comment]
Heyy @lsaudon also around here? PR looks good, just don't know if `a` instead of `_` is a common convention or from what rule this comes from.

Can't give more then that just a watcher here 😁

**Comment by lsaudon** [comment]
> Heyy @lsaudon also around here? PR looks good, just don't know if `a` instead of `_` is a common convention or from what rule this comes from.
> 
> Can't give more then that just a watcher here 😁

"_" must be used for private variables. I replaced with "one" because I didn't know what to put instead.

**Comment by lsaudon** [comment]
> Heyy @lsaudon also around here? PR looks good, just don't know if `a` instead of `_` is a common convention or from what rule this comes from.
> 
> Can't give more then that just a watcher here 😁

I try to update the problematic dependencies in smooth-app 😁

**Review by TesteurManiak — APPROVED** [review]
Changes seems ok to me.

**Comment by TesteurManiak** [comment]
Thanks for the contribution @lsaudon, your changes have been published on pub.dev in the [v1.3.0 of the package](https://pub.dev/packages/matomo_tracker/versions/1.3.0)

**Pull request merged**
