### PR TITLE
Release v4.0.0

### PR DESCRIPTION
**Pull request by TesteurManiak**
- [x] Add a Dispatching link in the summary
- [x] Add a deprecation notice for Matomo 3.x in the `README.md`
- [x] Add #97 to the `CHANGELOG.md`

### CODE REVIEW

**Comment by TesteurManiak** [comment]
Thanks for the feedbacks @EPNW-Eric!
I was expecting that some changes were left to do, this is why I've made this PR a draft. I will add them for a better visibility of what's left before the release.

**Comment by TesteurManiak** [comment]
The release might be delayed a bit, @MeixDev made some investigations and discovered that ad blockers might break flutter web applications that are using the package because of the `tracking_order_item.dart` file.
Renaming seemed to fix this but investigating a bit more wouldn't hurt.

**Comment by EPNW-Eric** [comment]
Hm that's actually very interesting... I would love to hear more about this (out of personal interest 😅).

Where those tests run with flutter release or development builds? Afaik release builds should do some minifying and type renaming automatically, so the file should not contain the word "tracking" there (what I would assume to be the problem, but again, would love to hear more about the details 😊).

**Comment by MeixDev** [comment]
It is true I only tried on Debug builds, with  the uBlock Origin extension on Firefox, for now.

If the production JS code is minified, which it indeed should be if only to reduce serve time, this would probably save us from trouble.

At the same time though, it's an annoying error to track when you're testing things (it makes the whole app crash while loading, but it doesn't log anything in the Flutter console, only in the browser's).

Some further investigations should be done, with other browsers and adblockers, and with extensions that only block tracking.

**Comment by EPNW-Eric** [comment]
I know that it might be kind of "late" to mention this now, but since this is going to be a major release it might be a good opportunity to make the parameters of the `track...` methods consistent: So methods take named (both, required and not required) parameters, some take positional ones. To me, it appears to be a bit arbitrary. I could have followed the logic to make things that should not be null positional and the rest optional named, but this is not the case since we have some things that are name `requried`. I personally would prefere a style where all `track...` parameters are named ones.

**Comment by TesteurManiak** [comment]
@MeixDev I'm going to merge this PR and release v4.0.0 on pub.dev, even if your issue with ad blockers persist, renaming a file so it won't be blocked shouldn't be a breaking change.

**Pull request merged**
