### PR TITLE
Add pause and resume capabilities with lock mechanism to prevent concurrent access

### PR DESCRIPTION
**Pull request by scolnet**
Hello team,

Thank you to develop this tracker for Matomo. 👍 
I noticed that the timer keeps running when the app is in the background.
So I added development to handle pause and resume timer if needed and I added a lock mechanism to prevent the queue from being processed concurrently if the processing is longer than the timer periodicity.

Example of use 

```
void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      MatomoTracker.instance.pause(); 
    } else if (state == AppLifecycleState.resumed){
      MatomoTracker.instance.resume();
    }
  }
```

I let you see if this development is interesting for the project.

Sébastien

### CODE REVIEW

**Comment by TesteurManiak** [comment]
Hi, thank you for your contribution, the restartable logic seems good to me but I wonder if a lock mechanism could be implemented without adding a new pub dependency to the package.
What do you think @Pierre-Monier @MeixDev ?

**Comment by Pierre-Monier** [comment]
I agree that in this case, `synchronized` could be an easily avoided dependency.  We can just implement a utility function or a private method to do this.

**Comment by TesteurManiak** [comment]
You can definitely avoid to add a dependency to `synchronized`.
Here's an utility class that you can use, based on the package and with the same API so you won't have to change your code:

```dart
import 'dart:async';

/// Simple lock implementation to prevent concurrent access to asynchronous
/// code.
///
/// Based on tekartik's [basic_lock.dart](https://github.com/tekartik/synchronized.dart/blob/master/synchronized/lib/src/basic_lock.dart)
class Lock {
  Future<dynamic>? last;

  bool get locked => last != null;

  Future<T> synchronized<T>(
    FutureOr<T> Function() func,
  ) async {
    final prev = last;
    final completer = Completer.sync();
    last = completer.future;
    try {
      if (prev != null) {
        await prev;
      }

      final result = func();
      return result;
    } finally {
      if (identical(last, completer.future)) {
        last = null;
      }
      completer.complete();
    }
  }
}
```
If it works the same for you and if you fix the analyzer warnings everything will be ok for me to merge your PR. (This might also solve #33 without removing the queue mecanism)

**Comment by scolnet** [comment]
Thanks for your feedbacks
Updates are done. 

Sébastien

**Review by TesteurManiak — APPROVED** [review]

**Pull request merged**
