### PR TITLE
feat: added option to toggle off cookieless

### PR DESCRIPTION
**Pull request by zvikarp**
Hi,

We have a use case where the user starts with cookieless turned on and we need to turn it off. This PR allows to change the the local storage without closing the app (= reinitializing the package).

Thank you for creating and maintaining the package, I really appreciate it!

### CODE REVIEW

**Review by TesteurManiak — APPROVED** [review]
Thanks for the contribution, LGTM!
Would love a review from another maintainer (cc @Pierre-Monier @MeixDev)
Otherwise I'll merge the PR 🙂

**Comment by TesteurManiak** [comment]
This should also fix #141

**Comment by TesteurManiak** [comment]
@zvikarp You'll also have to fix the failing check before this can be merged.

**Review by Pierre-Monier — APPROVED** [review]
LGTM

**Comment by TesteurManiak** [comment]
Perfect thanks @Pierre-Monier 💪

**Pull request merged**
