### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by EPNW-Eric**
From my understanding, this package uses the [Tracking HTTP API](https://developer.matomo.org/api-reference/tracking-api).

On some methods it was not clear to me what the parameters actually mean so I got through the code and tried to find out to which parameter of the dart API matches what parameter of the tracking API and just add these correspondences to the documentation.

I also fixed a mistake where it currently states that
https://github.com/Floating-Dartists/matomo-tracker/blob/2dbf25209c995762daf6461cbcfa5ca0952798ef/lib/src/matomo.dart#L111
where it should be `visitorId` instead.

Also, I wonder why `int` and not `num` is used for `eventValue` in `trackEvent`
https://github.com/Floating-Dartists/matomo-tracker/blob/2dbf25209c995762daf6461cbcfa5ca0952798ef/lib/src/matomo.dart#L395
because the tracking API states that it can be an int or float, but this should maybe be discussed in a separate issue.

I tried to not write code and just write documentation because I'm still not able to write tests (see #59...) but I could not resist to add some checks to the `trackDimensions` method 😅.

Moreover I think the concept of `_id` (which is `visitorId`), `cid` (which is `forcedId`) and `uid` (which is `userId`) is a bit confusing... I'd love to add some more explanations on that, but haven't understood it fully yet myself... For example, why can `visitorId` be set in initialization but not `userId`? What is the puropse of `forceId` if the user can not set it? Or can he actually set it somehow and I'm missing something?

Also I've not updated `CHANGELOG.md` and the `pubspec.yaml` yet because I belive there might be some discussions about these changes 😄.

### CODE REVIEW

**Review by TesteurManiak — APPROVED** [review]
LGTM, I'm okay with the added details on the documentation and the additional logic to check the dimensions is relevant, thank you for adding it. Also, thank you for targeting the `dev` branch to avoid a diminution in the code coverage on `main`.

Nonetheless, it would be great if you could take a bit of time to learn how to write some basic unit tests. As of now, if we merge this PR we'll have to write the test ourselves, for a small PR like this one, it's quite easy but if at some point you (or anybody else) were to make a larger contribution it would lock us out of a new release as wouldn't have unit tests for covering these changes.

**Comment by TesteurManiak** [comment]
About the unclear naming conventions for `_id`, `cid` and `uid` it is mostly legacy code from the [original package that we've forked](https://github.com/poitch/dart-matomo) a while ago. I don't mind changing those names but as this might lead to breaking changes in the public API it should probably be done by first keeping and deprecating the old getters. 🤔 

About the `userId` which is not set in the `initialize` method, it is also because of the initial forked code, it can probably be improved but there might be side effects with such a modification. For now, we, the maintainers, decided that it was not a priority to change this behavior as you can chain with a call to `setVisitorUserId` after the initialization.

**Comment by TesteurManiak** [comment]
(cc @Pierre-Monier do you think you can double check before I merge this)

**Comment by EPNW-Eric** [comment]
Yes, I think I'll have to look into units test, since I might need to implement campaigns for our usage in our next project...

About the id thing: I want to highlight that if I'm not mistaken, `forceId` is unnecessary, since the user can never set it at it will always be `null`. It is part of the `Visitor` class which belongs to the non-public API. This class is instantiated at two different places.

The first place is
https://github.com/Floating-Dartists/matomo-tracker/blob/2dbf25209c995762daf6461cbcfa5ca0952798ef/lib/src/matomo.dart#L160-L161
where `forceId` is not set at all, meaning that it is `null`.

The second place is
https://github.com/Floating-Dartists/matomo-tracker/blob/2dbf25209c995762daf6461cbcfa5ca0952798ef/lib/src/matomo.dart#L48-L56
where the `forceId` is simply keept from the previous instance, which at this point has to be `null`.

**Pull request merged**
